print('script_common:hello world')

Entity.addValueDef("level", 1, true, true, true, true)
Entity.addValueDef("exp", 0, true, true, true, true)
Entity.addValueDef("point", 10, true, true, true, true)
Entity.addValueDef("str", 0, true, true, true, true)
Entity.addValueDef("int", 0, true, true, true, true)
Entity.addValueDef("dex", 0, true, true, true, true)
Entity.addValueDef("vit", 0, true, true, true, true)
Entity.addValueDef("defaultDamage", 0, true, true, false, true)
Entity.addValueDef("defaultDefense", 0, true, true, false, true)
Entity.addValueDef("defaultmaxVp", 0, true, true, false, true)
Entity.addValueDef("quest", {}, true, true, true, true)
Entity.addValueDef("questStatus", false, true, true, true, true)
Entity.addValueDef("getQuest", false, true, true, true, true)